import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Table } from '../components/table/Table';
import { Person } from '../interfaces/Person';

const Home: NextPage = () => {

  const persons: Person[] = [{
    firstname: 'Andre', lastname: 'Kocher', age: 20, dateOfBirth: new Date('2001-12-05'), currentProfession: 'Student'
  }];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to my first TypeScript project</h1>
      <Table persons={persons} />
    </div>
  )
}

export default Home
